// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: pb/agent.proto

package agent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GuardLevelType int32

const (
	GuardLevelType_NoGuard  GuardLevelType = 0
	GuardLevelType_Governor GuardLevelType = 1
	GuardLevelType_Admiral  GuardLevelType = 2
	GuardLevelType_Captain  GuardLevelType = 3
)

// Enum value maps for GuardLevelType.
var (
	GuardLevelType_name = map[int32]string{
		0: "NoGuard",
		1: "Governor",
		2: "Admiral",
		3: "Captain",
	}
	GuardLevelType_value = map[string]int32{
		"NoGuard":  0,
		"Governor": 1,
		"Admiral":  2,
		"Captain":  3,
	}
)

func (x GuardLevelType) Enum() *GuardLevelType {
	p := new(GuardLevelType)
	*p = x
	return p
}

func (x GuardLevelType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GuardLevelType) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_agent_proto_enumTypes[0].Descriptor()
}

func (GuardLevelType) Type() protoreflect.EnumType {
	return &file_pb_agent_proto_enumTypes[0]
}

func (x GuardLevelType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GuardLevelType.Descriptor instead.
func (GuardLevelType) EnumDescriptor() ([]byte, []int) {
	return file_pb_agent_proto_rawDescGZIP(), []int{0}
}

type AgentControlResponse_StatusType int32

const (
	AgentControlResponse_OK  AgentControlResponse_StatusType = 0
	AgentControlResponse_Err AgentControlResponse_StatusType = 1
)

// Enum value maps for AgentControlResponse_StatusType.
var (
	AgentControlResponse_StatusType_name = map[int32]string{
		0: "OK",
		1: "Err",
	}
	AgentControlResponse_StatusType_value = map[string]int32{
		"OK":  0,
		"Err": 1,
	}
)

func (x AgentControlResponse_StatusType) Enum() *AgentControlResponse_StatusType {
	p := new(AgentControlResponse_StatusType)
	*p = x
	return p
}

func (x AgentControlResponse_StatusType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentControlResponse_StatusType) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_agent_proto_enumTypes[1].Descriptor()
}

func (AgentControlResponse_StatusType) Type() protoreflect.EnumType {
	return &file_pb_agent_proto_enumTypes[1]
}

func (x AgentControlResponse_StatusType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentControlResponse_StatusType.Descriptor instead.
func (AgentControlResponse_StatusType) EnumDescriptor() ([]byte, []int) {
	return file_pb_agent_proto_rawDescGZIP(), []int{0, 0}
}

type AgentInfo_AgentType int32

const (
	AgentInfo_UnknownAgent  AgentInfo_AgentType = 0
	AgentInfo_RealTimeAgent AgentInfo_AgentType = 1
	AgentInfo_PlaybackAgent AgentInfo_AgentType = 2
)

// Enum value maps for AgentInfo_AgentType.
var (
	AgentInfo_AgentType_name = map[int32]string{
		0: "UnknownAgent",
		1: "RealTimeAgent",
		2: "PlaybackAgent",
	}
	AgentInfo_AgentType_value = map[string]int32{
		"UnknownAgent":  0,
		"RealTimeAgent": 1,
		"PlaybackAgent": 2,
	}
)

func (x AgentInfo_AgentType) Enum() *AgentInfo_AgentType {
	p := new(AgentInfo_AgentType)
	*p = x
	return p
}

func (x AgentInfo_AgentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentInfo_AgentType) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_agent_proto_enumTypes[2].Descriptor()
}

func (AgentInfo_AgentType) Type() protoreflect.EnumType {
	return &file_pb_agent_proto_enumTypes[2]
}

func (x AgentInfo_AgentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentInfo_AgentType.Descriptor instead.
func (AgentInfo_AgentType) EnumDescriptor() ([]byte, []int) {
	return file_pb_agent_proto_rawDescGZIP(), []int{1, 0}
}

type AgentAction_AgentActionType int32

const (
	AgentAction_AddRoom AgentAction_AgentActionType = 0
	AgentAction_DelRoom AgentAction_AgentActionType = 1
)

// Enum value maps for AgentAction_AgentActionType.
var (
	AgentAction_AgentActionType_name = map[int32]string{
		0: "AddRoom",
		1: "DelRoom",
	}
	AgentAction_AgentActionType_value = map[string]int32{
		"AddRoom": 0,
		"DelRoom": 1,
	}
)

func (x AgentAction_AgentActionType) Enum() *AgentAction_AgentActionType {
	p := new(AgentAction_AgentActionType)
	*p = x
	return p
}

func (x AgentAction_AgentActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentAction_AgentActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_agent_proto_enumTypes[3].Descriptor()
}

func (AgentAction_AgentActionType) Type() protoreflect.EnumType {
	return &file_pb_agent_proto_enumTypes[3]
}

func (x AgentAction_AgentActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentAction_AgentActionType.Descriptor instead.
func (AgentAction_AgentActionType) EnumDescriptor() ([]byte, []int) {
	return file_pb_agent_proto_rawDescGZIP(), []int{3, 0}
}

type AgentStatus_BufferType int32

const (
	AgentStatus_Damaku       AgentStatus_BufferType = 0
	AgentStatus_Gift         AgentStatus_BufferType = 1
	AgentStatus_Guard        AgentStatus_BufferType = 2
	AgentStatus_SuperChat    AgentStatus_BufferType = 3
	AgentStatus_OnlineRank   AgentStatus_BufferType = 4
	AgentStatus_OnlineRankV2 AgentStatus_BufferType = 5
)

// Enum value maps for AgentStatus_BufferType.
var (
	AgentStatus_BufferType_name = map[int32]string{
		0: "Damaku",
		1: "Gift",
		2: "Guard",
		3: "SuperChat",
		4: "OnlineRank",
		5: "OnlineRankV2",
	}
	AgentStatus_BufferType_value = map[string]int32{
		"Damaku":       0,
		"Gift":         1,
		"Guard":        2,
		"SuperChat":    3,
		"OnlineRank":   4,
		"OnlineRankV2": 5,
	}
)

func (x AgentStatus_BufferType) Enum() *AgentStatus_BufferType {
	p := new(AgentStatus_BufferType)
	*p = x
	return p
}

func (x AgentStatus_BufferType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentStatus_BufferType) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_agent_proto_enumTypes[4].Descriptor()
}

func (AgentStatus_BufferType) Type() protoreflect.EnumType {
	return &file_pb_agent_proto_enumTypes[4]
}

func (x AgentStatus_BufferType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentStatus_BufferType.Descriptor instead.
func (AgentStatus_BufferType) EnumDescriptor() ([]byte, []int) {
	return file_pb_agent_proto_rawDescGZIP(), []int{4, 0}
}

type AgentStatus_MetaCacheType int32

const (
	AgentStatus_User  AgentStatus_MetaCacheType = 0
	AgentStatus_Medal AgentStatus_MetaCacheType = 1
)

// Enum value maps for AgentStatus_MetaCacheType.
var (
	AgentStatus_MetaCacheType_name = map[int32]string{
		0: "User",
		1: "Medal",
	}
	AgentStatus_MetaCacheType_value = map[string]int32{
		"User":  0,
		"Medal": 1,
	}
)

func (x AgentStatus_MetaCacheType) Enum() *AgentStatus_MetaCacheType {
	p := new(AgentStatus_MetaCacheType)
	*p = x
	return p
}

func (x AgentStatus_MetaCacheType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentStatus_MetaCacheType) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_agent_proto_enumTypes[5].Descriptor()
}

func (AgentStatus_MetaCacheType) Type() protoreflect.EnumType {
	return &file_pb_agent_proto_enumTypes[5]
}

func (x AgentStatus_MetaCacheType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentStatus_MetaCacheType.Descriptor instead.
func (AgentStatus_MetaCacheType) EnumDescriptor() ([]byte, []int) {
	return file_pb_agent_proto_rawDescGZIP(), []int{4, 1}
}

type BasicMsgMeta_TraceStep int32

const (
	BasicMsgMeta_Wait    BasicMsgMeta_TraceStep = 0
	BasicMsgMeta_Process BasicMsgMeta_TraceStep = 1
)

// Enum value maps for BasicMsgMeta_TraceStep.
var (
	BasicMsgMeta_TraceStep_name = map[int32]string{
		0: "Wait",
		1: "Process",
	}
	BasicMsgMeta_TraceStep_value = map[string]int32{
		"Wait":    0,
		"Process": 1,
	}
)

func (x BasicMsgMeta_TraceStep) Enum() *BasicMsgMeta_TraceStep {
	p := new(BasicMsgMeta_TraceStep)
	*p = x
	return p
}

func (x BasicMsgMeta_TraceStep) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BasicMsgMeta_TraceStep) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_agent_proto_enumTypes[6].Descriptor()
}

func (BasicMsgMeta_TraceStep) Type() protoreflect.EnumType {
	return &file_pb_agent_proto_enumTypes[6]
}

func (x BasicMsgMeta_TraceStep) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BasicMsgMeta_TraceStep.Descriptor instead.
func (BasicMsgMeta_TraceStep) EnumDescriptor() ([]byte, []int) {
	return file_pb_agent_proto_rawDescGZIP(), []int{7, 0}
}

type Guard_GuardGiftType int32

const (
	Guard_UnknownType Guard_GuardGiftType = 0
	Guard_Governor    Guard_GuardGiftType = 10001
	Guard_Admiral     Guard_GuardGiftType = 10002
	Guard_Captain     Guard_GuardGiftType = 10003
)

// Enum value maps for Guard_GuardGiftType.
var (
	Guard_GuardGiftType_name = map[int32]string{
		0:     "UnknownType",
		10001: "Governor",
		10002: "Admiral",
		10003: "Captain",
	}
	Guard_GuardGiftType_value = map[string]int32{
		"UnknownType": 0,
		"Governor":    10001,
		"Admiral":     10002,
		"Captain":     10003,
	}
)

func (x Guard_GuardGiftType) Enum() *Guard_GuardGiftType {
	p := new(Guard_GuardGiftType)
	*p = x
	return p
}

func (x Guard_GuardGiftType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Guard_GuardGiftType) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_agent_proto_enumTypes[7].Descriptor()
}

func (Guard_GuardGiftType) Type() protoreflect.EnumType {
	return &file_pb_agent_proto_enumTypes[7]
}

func (x Guard_GuardGiftType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Guard_GuardGiftType.Descriptor instead.
func (Guard_GuardGiftType) EnumDescriptor() ([]byte, []int) {
	return file_pb_agent_proto_rawDescGZIP(), []int{10, 0}
}

// normal response for request msg
type AgentControlResponse struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Status        AgentControlResponse_StatusType `protobuf:"varint,1,opt,name=Status,proto3,enum=pb.AgentControlResponse_StatusType" json:"Status,omitempty"` // 0:OK, 1:Error
	Error         *string                         `protobuf:"bytes,2,opt,name=Error,proto3,oneof" json:"Error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentControlResponse) Reset() {
	*x = AgentControlResponse{}
	mi := &file_pb_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentControlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentControlResponse) ProtoMessage() {}

func (x *AgentControlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentControlResponse.ProtoReflect.Descriptor instead.
func (*AgentControlResponse) Descriptor() ([]byte, []int) {
	return file_pb_agent_proto_rawDescGZIP(), []int{0}
}

func (x *AgentControlResponse) GetStatus() AgentControlResponse_StatusType {
	if x != nil {
		return x.Status
	}
	return AgentControlResponse_OK
}

func (x *AgentControlResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

// bind to agent.info when init
type AgentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Type          AgentInfo_AgentType    `protobuf:"varint,2,opt,name=Type,proto3,enum=pb.AgentInfo_AgentType" json:"Type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentInfo) Reset() {
	*x = AgentInfo{}
	mi := &file_pb_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentInfo) ProtoMessage() {}

func (x *AgentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pb_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentInfo.ProtoReflect.Descriptor instead.
func (*AgentInfo) Descriptor() ([]byte, []int) {
	return file_pb_agent_proto_rawDescGZIP(), []int{1}
}

func (x *AgentInfo) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *AgentInfo) GetType() AgentInfo_AgentType {
	if x != nil {
		return x.Type
	}
	return AgentInfo_UnknownAgent
}

// bind to control request agent.[AgentID].init
type AgentInit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BUVID         string                 `protobuf:"bytes,1,opt,name=BUVID,proto3" json:"BUVID,omitempty"`
	UID           uint64                 `protobuf:"varint,2,opt,name=UID,proto3" json:"UID,omitempty"`
	Cookie        string                 `protobuf:"bytes,3,opt,name=Cookie,proto3" json:"Cookie,omitempty"`
	UA            *string                `protobuf:"bytes,4,opt,name=UA,proto3,oneof" json:"UA,omitempty"`
	Header        map[string]string      `protobuf:"bytes,5,rep,name=Header,proto3" json:"Header,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	PriorityMode  *uint32                `protobuf:"varint,6,opt,name=PriorityMode,proto3,oneof" json:"PriorityMode,omitempty"` // defined const at github.com/FishZe/go-bili-chat/client:PriorityMode
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentInit) Reset() {
	*x = AgentInit{}
	mi := &file_pb_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentInit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentInit) ProtoMessage() {}

func (x *AgentInit) ProtoReflect() protoreflect.Message {
	mi := &file_pb_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentInit.ProtoReflect.Descriptor instead.
func (*AgentInit) Descriptor() ([]byte, []int) {
	return file_pb_agent_proto_rawDescGZIP(), []int{2}
}

func (x *AgentInit) GetBUVID() string {
	if x != nil {
		return x.BUVID
	}
	return ""
}

func (x *AgentInit) GetUID() uint64 {
	if x != nil {
		return x.UID
	}
	return 0
}

func (x *AgentInit) GetCookie() string {
	if x != nil {
		return x.Cookie
	}
	return ""
}

func (x *AgentInit) GetUA() string {
	if x != nil && x.UA != nil {
		return *x.UA
	}
	return ""
}

func (x *AgentInit) GetHeader() map[string]string {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *AgentInit) GetPriorityMode() uint32 {
	if x != nil && x.PriorityMode != nil {
		return *x.PriorityMode
	}
	return 0
}

// bind to control request agent.[AgentID].action
type AgentAction struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Type          AgentAction_AgentActionType `protobuf:"varint,1,opt,name=Type,proto3,enum=pb.AgentAction_AgentActionType" json:"Type,omitempty"`
	RoomID        *uint64                     `protobuf:"varint,2,opt,name=RoomID,proto3,oneof" json:"RoomID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentAction) Reset() {
	*x = AgentAction{}
	mi := &file_pb_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentAction) ProtoMessage() {}

func (x *AgentAction) ProtoReflect() protoreflect.Message {
	mi := &file_pb_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentAction.ProtoReflect.Descriptor instead.
func (*AgentAction) Descriptor() ([]byte, []int) {
	return file_pb_agent_proto_rawDescGZIP(), []int{3}
}

func (x *AgentAction) GetType() AgentAction_AgentActionType {
	if x != nil {
		return x.Type
	}
	return AgentAction_AddRoom
}

func (x *AgentAction) GetRoomID() uint64 {
	if x != nil && x.RoomID != nil {
		return *x.RoomID
	}
	return 0
}

// bind to agent.status
type AgentStatus struct {
	state            protoimpl.MessageState               `protogen:"open.v1"`
	Meta             *BasicMsgMeta                        `protobuf:"bytes,1,opt,name=Meta,proto3" json:"Meta,omitempty"`
	Watching         []uint64                             `protobuf:"varint,2,rep,packed,name=Watching,proto3" json:"Watching,omitempty"`
	BufferUsed       uint32                               `protobuf:"varint,3,opt,name=BufferUsed,proto3" json:"BufferUsed,omitempty"`
	BufferEventCount map[int32]int32                      `protobuf:"bytes,4,rep,name=BufferEventCount,proto3" json:"BufferEventCount,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // BufferType:count
	MetaCache        map[int32]*AgentStatus_MetaCacheInfo `protobuf:"bytes,5,rep,name=MetaCache,proto3" json:"MetaCache,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`                // MetaCacheType:MetaCacheInfo
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AgentStatus) Reset() {
	*x = AgentStatus{}
	mi := &file_pb_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentStatus) ProtoMessage() {}

func (x *AgentStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pb_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentStatus.ProtoReflect.Descriptor instead.
func (*AgentStatus) Descriptor() ([]byte, []int) {
	return file_pb_agent_proto_rawDescGZIP(), []int{4}
}

func (x *AgentStatus) GetMeta() *BasicMsgMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *AgentStatus) GetWatching() []uint64 {
	if x != nil {
		return x.Watching
	}
	return nil
}

func (x *AgentStatus) GetBufferUsed() uint32 {
	if x != nil {
		return x.BufferUsed
	}
	return 0
}

func (x *AgentStatus) GetBufferEventCount() map[int32]int32 {
	if x != nil {
		return x.BufferEventCount
	}
	return nil
}

func (x *AgentStatus) GetMetaCache() map[int32]*AgentStatus_MetaCacheInfo {
	if x != nil {
		return x.MetaCache
	}
	return nil
}

// bind to request stream.fansMedal
type FansMedalMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UID           uint64                 `protobuf:"varint,1,opt,name=UID,proto3" json:"UID,omitempty"`
	RoomUID       uint64                 `protobuf:"varint,2,opt,name=RoomUID,proto3" json:"RoomUID,omitempty"` // target user id
	Name          string                 `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Level         uint32                 `protobuf:"varint,4,opt,name=Level,proto3" json:"Level,omitempty"`
	Light         bool                   `protobuf:"varint,5,opt,name=Light,proto3" json:"Light,omitempty"`
	GuardLevel    GuardLevelType         `protobuf:"varint,6,opt,name=GuardLevel,proto3,enum=pb.GuardLevelType" json:"GuardLevel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FansMedalMeta) Reset() {
	*x = FansMedalMeta{}
	mi := &file_pb_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FansMedalMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FansMedalMeta) ProtoMessage() {}

func (x *FansMedalMeta) ProtoReflect() protoreflect.Message {
	mi := &file_pb_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FansMedalMeta.ProtoReflect.Descriptor instead.
func (*FansMedalMeta) Descriptor() ([]byte, []int) {
	return file_pb_agent_proto_rawDescGZIP(), []int{5}
}

func (x *FansMedalMeta) GetUID() uint64 {
	if x != nil {
		return x.UID
	}
	return 0
}

func (x *FansMedalMeta) GetRoomUID() uint64 {
	if x != nil {
		return x.RoomUID
	}
	return 0
}

func (x *FansMedalMeta) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FansMedalMeta) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *FansMedalMeta) GetLight() bool {
	if x != nil {
		return x.Light
	}
	return false
}

func (x *FansMedalMeta) GetGuardLevel() GuardLevelType {
	if x != nil {
		return x.GuardLevel
	}
	return GuardLevelType_NoGuard
}

// bind to request stream.userInfo
type UserInfoMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UID           uint64                 `protobuf:"varint,1,opt,name=UID,proto3" json:"UID,omitempty"`
	UserName      string                 `protobuf:"bytes,2,opt,name=UserName,proto3" json:"UserName,omitempty"`
	Face          *string                `protobuf:"bytes,3,opt,name=Face,proto3,oneof" json:"Face,omitempty"`                // available at damaku,gift,superChat,onlineRankV2
	Level         *uint32                `protobuf:"varint,4,opt,name=Level,proto3,oneof" json:"Level,omitempty"`             // available at superChat
	WealthLevel   *uint32                `protobuf:"varint,5,opt,name=WealthLevel,proto3,oneof" json:"WealthLevel,omitempty"` // available at gift
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfoMeta) Reset() {
	*x = UserInfoMeta{}
	mi := &file_pb_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfoMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoMeta) ProtoMessage() {}

func (x *UserInfoMeta) ProtoReflect() protoreflect.Message {
	mi := &file_pb_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoMeta.ProtoReflect.Descriptor instead.
func (*UserInfoMeta) Descriptor() ([]byte, []int) {
	return file_pb_agent_proto_rawDescGZIP(), []int{6}
}

func (x *UserInfoMeta) GetUID() uint64 {
	if x != nil {
		return x.UID
	}
	return 0
}

func (x *UserInfoMeta) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *UserInfoMeta) GetFace() string {
	if x != nil && x.Face != nil {
		return *x.Face
	}
	return ""
}

func (x *UserInfoMeta) GetLevel() uint32 {
	if x != nil && x.Level != nil {
		return *x.Level
	}
	return 0
}

func (x *UserInfoMeta) GetWealthLevel() uint32 {
	if x != nil && x.WealthLevel != nil {
		return *x.WealthLevel
	}
	return 0
}

type BasicMsgMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint32                 `protobuf:"varint,1,opt,name=Version,proto3" json:"Version,omitempty"`
	Agent         string                 `protobuf:"bytes,2,opt,name=Agent,proto3" json:"Agent,omitempty"`                                                                             // AgentID
	RoomID        *uint64                `protobuf:"varint,3,opt,name=RoomID,proto3,oneof" json:"RoomID,omitempty"`                                                                    // available at msg
	TimeStamp     uint64                 `protobuf:"varint,4,opt,name=TimeStamp,proto3" json:"TimeStamp,omitempty"`                                                                    // MilliTimestamp
	Trace         map[int32]uint64       `protobuf:"bytes,5,rep,name=Trace,proto3" json:"Trace,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // TraceStep:Microseconds, available at msg
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BasicMsgMeta) Reset() {
	*x = BasicMsgMeta{}
	mi := &file_pb_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BasicMsgMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasicMsgMeta) ProtoMessage() {}

func (x *BasicMsgMeta) ProtoReflect() protoreflect.Message {
	mi := &file_pb_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasicMsgMeta.ProtoReflect.Descriptor instead.
func (*BasicMsgMeta) Descriptor() ([]byte, []int) {
	return file_pb_agent_proto_rawDescGZIP(), []int{7}
}

func (x *BasicMsgMeta) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *BasicMsgMeta) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

func (x *BasicMsgMeta) GetRoomID() uint64 {
	if x != nil && x.RoomID != nil {
		return *x.RoomID
	}
	return 0
}

func (x *BasicMsgMeta) GetTimeStamp() uint64 {
	if x != nil {
		return x.TimeStamp
	}
	return 0
}

func (x *BasicMsgMeta) GetTrace() map[int32]uint64 {
	if x != nil {
		return x.Trace
	}
	return nil
}

// bind to stream.damaku
type Damaku struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *BasicMsgMeta          `protobuf:"bytes,1,opt,name=Meta,proto3" json:"Meta,omitempty"`
	UID           uint64                 `protobuf:"varint,2,opt,name=UID,proto3" json:"UID,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=Content,proto3" json:"Content,omitempty"`
	Medal         uint64                 `protobuf:"varint,4,opt,name=Medal,proto3" json:"Medal,omitempty"` // target user id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Damaku) Reset() {
	*x = Damaku{}
	mi := &file_pb_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Damaku) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Damaku) ProtoMessage() {}

func (x *Damaku) ProtoReflect() protoreflect.Message {
	mi := &file_pb_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Damaku.ProtoReflect.Descriptor instead.
func (*Damaku) Descriptor() ([]byte, []int) {
	return file_pb_agent_proto_rawDescGZIP(), []int{8}
}

func (x *Damaku) GetMeta() *BasicMsgMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Damaku) GetUID() uint64 {
	if x != nil {
		return x.UID
	}
	return 0
}

func (x *Damaku) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Damaku) GetMedal() uint64 {
	if x != nil {
		return x.Medal
	}
	return 0
}

// bind to stream.gift
type Gift struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *BasicMsgMeta          `protobuf:"bytes,1,opt,name=Meta,proto3" json:"Meta,omitempty"`
	TID           uint64                 `protobuf:"varint,2,opt,name=TID,proto3" json:"TID,omitempty"` // gift msg id
	UID           uint64                 `protobuf:"varint,3,opt,name=UID,proto3" json:"UID,omitempty"`
	Count         uint32                 `protobuf:"varint,4,opt,name=Count,proto3" json:"Count,omitempty"`
	Info          *Gift_GiftInfo         `protobuf:"bytes,5,opt,name=Info,proto3" json:"Info,omitempty"`
	OriginalInfo  *Gift_GiftInfo         `protobuf:"bytes,6,opt,name=OriginalInfo,proto3" json:"OriginalInfo,omitempty"` // include blind gift, or same as info
	Medal         uint64                 `protobuf:"varint,7,opt,name=Medal,proto3" json:"Medal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Gift) Reset() {
	*x = Gift{}
	mi := &file_pb_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Gift) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gift) ProtoMessage() {}

func (x *Gift) ProtoReflect() protoreflect.Message {
	mi := &file_pb_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gift.ProtoReflect.Descriptor instead.
func (*Gift) Descriptor() ([]byte, []int) {
	return file_pb_agent_proto_rawDescGZIP(), []int{9}
}

func (x *Gift) GetMeta() *BasicMsgMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Gift) GetTID() uint64 {
	if x != nil {
		return x.TID
	}
	return 0
}

func (x *Gift) GetUID() uint64 {
	if x != nil {
		return x.UID
	}
	return 0
}

func (x *Gift) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *Gift) GetInfo() *Gift_GiftInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *Gift) GetOriginalInfo() *Gift_GiftInfo {
	if x != nil {
		return x.OriginalInfo
	}
	return nil
}

func (x *Gift) GetMedal() uint64 {
	if x != nil {
		return x.Medal
	}
	return 0
}

// bind to stream.guard
type Guard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *BasicMsgMeta          `protobuf:"bytes,1,opt,name=Meta,proto3" json:"Meta,omitempty"`
	UID           uint64                 `protobuf:"varint,2,opt,name=UID,proto3" json:"UID,omitempty"`
	Price         uint32                 `protobuf:"varint,3,opt,name=Price,proto3" json:"Price,omitempty"` // gold_seeds, = battery / 100 = RMB / 1000
	GiftType      Guard_GuardGiftType    `protobuf:"varint,4,opt,name=GiftType,proto3,enum=pb.Guard_GuardGiftType" json:"GiftType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Guard) Reset() {
	*x = Guard{}
	mi := &file_pb_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Guard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Guard) ProtoMessage() {}

func (x *Guard) ProtoReflect() protoreflect.Message {
	mi := &file_pb_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Guard.ProtoReflect.Descriptor instead.
func (*Guard) Descriptor() ([]byte, []int) {
	return file_pb_agent_proto_rawDescGZIP(), []int{10}
}

func (x *Guard) GetMeta() *BasicMsgMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Guard) GetUID() uint64 {
	if x != nil {
		return x.UID
	}
	return 0
}

func (x *Guard) GetPrice() uint32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Guard) GetGiftType() Guard_GuardGiftType {
	if x != nil {
		return x.GiftType
	}
	return Guard_UnknownType
}

// bind to stream.superChat
type SuperChat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *BasicMsgMeta          `protobuf:"bytes,1,opt,name=Meta,proto3" json:"Meta,omitempty"`
	ID            uint64                 `protobuf:"varint,2,opt,name=ID,proto3" json:"ID,omitempty"` // sc id
	UID           uint64                 `protobuf:"varint,3,opt,name=UID,proto3" json:"UID,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=Message,proto3" json:"Message,omitempty"`
	MessageTrans  string                 `protobuf:"bytes,5,opt,name=MessageTrans,proto3" json:"MessageTrans,omitempty"`
	Price         uint32                 `protobuf:"varint,6,opt,name=Price,proto3" json:"Price,omitempty"` // RMB, = battery / 10
	Medal         uint64                 `protobuf:"varint,7,opt,name=Medal,proto3" json:"Medal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuperChat) Reset() {
	*x = SuperChat{}
	mi := &file_pb_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuperChat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuperChat) ProtoMessage() {}

func (x *SuperChat) ProtoReflect() protoreflect.Message {
	mi := &file_pb_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuperChat.ProtoReflect.Descriptor instead.
func (*SuperChat) Descriptor() ([]byte, []int) {
	return file_pb_agent_proto_rawDescGZIP(), []int{11}
}

func (x *SuperChat) GetMeta() *BasicMsgMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *SuperChat) GetID() uint64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *SuperChat) GetUID() uint64 {
	if x != nil {
		return x.UID
	}
	return 0
}

func (x *SuperChat) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SuperChat) GetMessageTrans() string {
	if x != nil {
		return x.MessageTrans
	}
	return ""
}

func (x *SuperChat) GetPrice() uint32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *SuperChat) GetMedal() uint64 {
	if x != nil {
		return x.Medal
	}
	return 0
}

// bind to stream.online
type OnlineRankCount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *BasicMsgMeta          `protobuf:"bytes,1,opt,name=Meta,proto3" json:"Meta,omitempty"`
	Count         uint32                 `protobuf:"varint,2,opt,name=Count,proto3" json:"Count,omitempty"`
	Online        uint32                 `protobuf:"varint,3,opt,name=Online,proto3" json:"Online,omitempty"` // current using
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnlineRankCount) Reset() {
	*x = OnlineRankCount{}
	mi := &file_pb_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnlineRankCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineRankCount) ProtoMessage() {}

func (x *OnlineRankCount) ProtoReflect() protoreflect.Message {
	mi := &file_pb_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineRankCount.ProtoReflect.Descriptor instead.
func (*OnlineRankCount) Descriptor() ([]byte, []int) {
	return file_pb_agent_proto_rawDescGZIP(), []int{12}
}

func (x *OnlineRankCount) GetMeta() *BasicMsgMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *OnlineRankCount) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *OnlineRankCount) GetOnline() uint32 {
	if x != nil {
		return x.Online
	}
	return 0
}

// bind to stream.onlineV2
type OnlineRankV2 struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Meta          *BasicMsgMeta                  `protobuf:"bytes,1,opt,name=Meta,proto3" json:"Meta,omitempty"`
	List          []*OnlineRankV2_OnlineRankList `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnlineRankV2) Reset() {
	*x = OnlineRankV2{}
	mi := &file_pb_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnlineRankV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineRankV2) ProtoMessage() {}

func (x *OnlineRankV2) ProtoReflect() protoreflect.Message {
	mi := &file_pb_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineRankV2.ProtoReflect.Descriptor instead.
func (*OnlineRankV2) Descriptor() ([]byte, []int) {
	return file_pb_agent_proto_rawDescGZIP(), []int{13}
}

func (x *OnlineRankV2) GetMeta() *BasicMsgMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *OnlineRankV2) GetList() []*OnlineRankV2_OnlineRankList {
	if x != nil {
		return x.List
	}
	return nil
}

type AgentStatus_MetaCacheInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Buffer        uint32                 `protobuf:"varint,1,opt,name=Buffer,proto3" json:"Buffer,omitempty"` // meta indexer queue
	Cached        uint32                 `protobuf:"varint,2,opt,name=Cached,proto3" json:"Cached,omitempty"`
	Hits          int64                  `protobuf:"varint,3,opt,name=Hits,proto3" json:"Hits,omitempty"`
	Misses        int64                  `protobuf:"varint,4,opt,name=Misses,proto3" json:"Misses,omitempty"`
	DelHits       int64                  `protobuf:"varint,5,opt,name=DelHits,proto3" json:"DelHits,omitempty"`
	DelMisses     int64                  `protobuf:"varint,6,opt,name=DelMisses,proto3" json:"DelMisses,omitempty"`
	Collisions    int64                  `protobuf:"varint,7,opt,name=Collisions,proto3" json:"Collisions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentStatus_MetaCacheInfo) Reset() {
	*x = AgentStatus_MetaCacheInfo{}
	mi := &file_pb_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentStatus_MetaCacheInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentStatus_MetaCacheInfo) ProtoMessage() {}

func (x *AgentStatus_MetaCacheInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pb_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentStatus_MetaCacheInfo.ProtoReflect.Descriptor instead.
func (*AgentStatus_MetaCacheInfo) Descriptor() ([]byte, []int) {
	return file_pb_agent_proto_rawDescGZIP(), []int{4, 2}
}

func (x *AgentStatus_MetaCacheInfo) GetBuffer() uint32 {
	if x != nil {
		return x.Buffer
	}
	return 0
}

func (x *AgentStatus_MetaCacheInfo) GetCached() uint32 {
	if x != nil {
		return x.Cached
	}
	return 0
}

func (x *AgentStatus_MetaCacheInfo) GetHits() int64 {
	if x != nil {
		return x.Hits
	}
	return 0
}

func (x *AgentStatus_MetaCacheInfo) GetMisses() int64 {
	if x != nil {
		return x.Misses
	}
	return 0
}

func (x *AgentStatus_MetaCacheInfo) GetDelHits() int64 {
	if x != nil {
		return x.DelHits
	}
	return 0
}

func (x *AgentStatus_MetaCacheInfo) GetDelMisses() int64 {
	if x != nil {
		return x.DelMisses
	}
	return 0
}

func (x *AgentStatus_MetaCacheInfo) GetCollisions() int64 {
	if x != nil {
		return x.Collisions
	}
	return 0
}

type Gift_GiftInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            uint32                 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Price         uint32                 `protobuf:"varint,3,opt,name=Price,proto3" json:"Price,omitempty"` // gold_seeds, = battery / 100 = RMB / 1000
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Gift_GiftInfo) Reset() {
	*x = Gift_GiftInfo{}
	mi := &file_pb_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Gift_GiftInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gift_GiftInfo) ProtoMessage() {}

func (x *Gift_GiftInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pb_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gift_GiftInfo.ProtoReflect.Descriptor instead.
func (*Gift_GiftInfo) Descriptor() ([]byte, []int) {
	return file_pb_agent_proto_rawDescGZIP(), []int{9, 0}
}

func (x *Gift_GiftInfo) GetID() uint32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Gift_GiftInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Gift_GiftInfo) GetPrice() uint32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type OnlineRankV2_OnlineRankList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rank          uint32                 `protobuf:"varint,1,opt,name=Rank,proto3" json:"Rank,omitempty"`
	Score         uint32                 `protobuf:"varint,2,opt,name=Score,proto3" json:"Score,omitempty"`
	UID           uint64                 `protobuf:"varint,3,opt,name=UID,proto3" json:"UID,omitempty"`
	GuardLevel    GuardLevelType         `protobuf:"varint,4,opt,name=GuardLevel,proto3,enum=pb.GuardLevelType" json:"GuardLevel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnlineRankV2_OnlineRankList) Reset() {
	*x = OnlineRankV2_OnlineRankList{}
	mi := &file_pb_agent_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnlineRankV2_OnlineRankList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineRankV2_OnlineRankList) ProtoMessage() {}

func (x *OnlineRankV2_OnlineRankList) ProtoReflect() protoreflect.Message {
	mi := &file_pb_agent_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineRankV2_OnlineRankList.ProtoReflect.Descriptor instead.
func (*OnlineRankV2_OnlineRankList) Descriptor() ([]byte, []int) {
	return file_pb_agent_proto_rawDescGZIP(), []int{13, 0}
}

func (x *OnlineRankV2_OnlineRankList) GetRank() uint32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *OnlineRankV2_OnlineRankList) GetScore() uint32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *OnlineRankV2_OnlineRankList) GetUID() uint64 {
	if x != nil {
		return x.UID
	}
	return 0
}

func (x *OnlineRankV2_OnlineRankList) GetGuardLevel() GuardLevelType {
	if x != nil {
		return x.GuardLevel
	}
	return GuardLevelType_NoGuard
}

var File_pb_agent_proto protoreflect.FileDescriptor

const file_pb_agent_proto_rawDesc = "" +
	"\n" +
	"\x0epb/agent.proto\x12\x02pb\"\x97\x01\n" +
	"\x14AgentControlResponse\x12;\n" +
	"\x06Status\x18\x01 \x01(\x0e2#.pb.AgentControlResponse.StatusTypeR\x06Status\x12\x19\n" +
	"\x05Error\x18\x02 \x01(\tH\x00R\x05Error\x88\x01\x01\"\x1d\n" +
	"\n" +
	"StatusType\x12\x06\n" +
	"\x02OK\x10\x00\x12\a\n" +
	"\x03Err\x10\x01B\b\n" +
	"\x06_Error\"\x8d\x01\n" +
	"\tAgentInfo\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12+\n" +
	"\x04Type\x18\x02 \x01(\x0e2\x17.pb.AgentInfo.AgentTypeR\x04Type\"C\n" +
	"\tAgentType\x12\x10\n" +
	"\fUnknownAgent\x10\x00\x12\x11\n" +
	"\rRealTimeAgent\x10\x01\x12\x11\n" +
	"\rPlaybackAgent\x10\x02\"\x8f\x02\n" +
	"\tAgentInit\x12\x14\n" +
	"\x05BUVID\x18\x01 \x01(\tR\x05BUVID\x12\x10\n" +
	"\x03UID\x18\x02 \x01(\x04R\x03UID\x12\x16\n" +
	"\x06Cookie\x18\x03 \x01(\tR\x06Cookie\x12\x13\n" +
	"\x02UA\x18\x04 \x01(\tH\x00R\x02UA\x88\x01\x01\x121\n" +
	"\x06Header\x18\x05 \x03(\v2\x19.pb.AgentInit.HeaderEntryR\x06Header\x12'\n" +
	"\fPriorityMode\x18\x06 \x01(\rH\x01R\fPriorityMode\x88\x01\x01\x1a9\n" +
	"\vHeaderEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x05\n" +
	"\x03_UAB\x0f\n" +
	"\r_PriorityMode\"\x97\x01\n" +
	"\vAgentAction\x123\n" +
	"\x04Type\x18\x01 \x01(\x0e2\x1f.pb.AgentAction.AgentActionTypeR\x04Type\x12\x1b\n" +
	"\x06RoomID\x18\x02 \x01(\x04H\x00R\x06RoomID\x88\x01\x01\"+\n" +
	"\x0fAgentActionType\x12\v\n" +
	"\aAddRoom\x10\x00\x12\v\n" +
	"\aDelRoom\x10\x01B\t\n" +
	"\a_RoomID\"\xee\x05\n" +
	"\vAgentStatus\x12$\n" +
	"\x04Meta\x18\x01 \x01(\v2\x10.pb.BasicMsgMetaR\x04Meta\x12\x1a\n" +
	"\bWatching\x18\x02 \x03(\x04R\bWatching\x12\x1e\n" +
	"\n" +
	"BufferUsed\x18\x03 \x01(\rR\n" +
	"BufferUsed\x12Q\n" +
	"\x10BufferEventCount\x18\x04 \x03(\v2%.pb.AgentStatus.BufferEventCountEntryR\x10BufferEventCount\x12<\n" +
	"\tMetaCache\x18\x05 \x03(\v2\x1e.pb.AgentStatus.MetaCacheEntryR\tMetaCache\x1aC\n" +
	"\x15BufferEventCountEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1a[\n" +
	"\x0eMetaCacheEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x123\n" +
	"\x05value\x18\x02 \x01(\v2\x1d.pb.AgentStatus.MetaCacheInfoR\x05value:\x028\x01\x1a\xc3\x01\n" +
	"\rMetaCacheInfo\x12\x16\n" +
	"\x06Buffer\x18\x01 \x01(\rR\x06Buffer\x12\x16\n" +
	"\x06Cached\x18\x02 \x01(\rR\x06Cached\x12\x12\n" +
	"\x04Hits\x18\x03 \x01(\x03R\x04Hits\x12\x16\n" +
	"\x06Misses\x18\x04 \x01(\x03R\x06Misses\x12\x18\n" +
	"\aDelHits\x18\x05 \x01(\x03R\aDelHits\x12\x1c\n" +
	"\tDelMisses\x18\x06 \x01(\x03R\tDelMisses\x12\x1e\n" +
	"\n" +
	"Collisions\x18\a \x01(\x03R\n" +
	"Collisions\"^\n" +
	"\n" +
	"BufferType\x12\n" +
	"\n" +
	"\x06Damaku\x10\x00\x12\b\n" +
	"\x04Gift\x10\x01\x12\t\n" +
	"\x05Guard\x10\x02\x12\r\n" +
	"\tSuperChat\x10\x03\x12\x0e\n" +
	"\n" +
	"OnlineRank\x10\x04\x12\x10\n" +
	"\fOnlineRankV2\x10\x05\"$\n" +
	"\rMetaCacheType\x12\b\n" +
	"\x04User\x10\x00\x12\t\n" +
	"\x05Medal\x10\x01\"\xaf\x01\n" +
	"\rFansMedalMeta\x12\x10\n" +
	"\x03UID\x18\x01 \x01(\x04R\x03UID\x12\x18\n" +
	"\aRoomUID\x18\x02 \x01(\x04R\aRoomUID\x12\x12\n" +
	"\x04Name\x18\x03 \x01(\tR\x04Name\x12\x14\n" +
	"\x05Level\x18\x04 \x01(\rR\x05Level\x12\x14\n" +
	"\x05Light\x18\x05 \x01(\bR\x05Light\x122\n" +
	"\n" +
	"GuardLevel\x18\x06 \x01(\x0e2\x12.pb.GuardLevelTypeR\n" +
	"GuardLevel\"\xba\x01\n" +
	"\fUserInfoMeta\x12\x10\n" +
	"\x03UID\x18\x01 \x01(\x04R\x03UID\x12\x1a\n" +
	"\bUserName\x18\x02 \x01(\tR\bUserName\x12\x17\n" +
	"\x04Face\x18\x03 \x01(\tH\x00R\x04Face\x88\x01\x01\x12\x19\n" +
	"\x05Level\x18\x04 \x01(\rH\x01R\x05Level\x88\x01\x01\x12%\n" +
	"\vWealthLevel\x18\x05 \x01(\rH\x02R\vWealthLevel\x88\x01\x01B\a\n" +
	"\x05_FaceB\b\n" +
	"\x06_LevelB\x0e\n" +
	"\f_WealthLevel\"\x95\x02\n" +
	"\fBasicMsgMeta\x12\x18\n" +
	"\aVersion\x18\x01 \x01(\rR\aVersion\x12\x14\n" +
	"\x05Agent\x18\x02 \x01(\tR\x05Agent\x12\x1b\n" +
	"\x06RoomID\x18\x03 \x01(\x04H\x00R\x06RoomID\x88\x01\x01\x12\x1c\n" +
	"\tTimeStamp\x18\x04 \x01(\x04R\tTimeStamp\x121\n" +
	"\x05Trace\x18\x05 \x03(\v2\x1b.pb.BasicMsgMeta.TraceEntryR\x05Trace\x1a8\n" +
	"\n" +
	"TraceEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\"\"\n" +
	"\tTraceStep\x12\b\n" +
	"\x04Wait\x10\x00\x12\v\n" +
	"\aProcess\x10\x01B\t\n" +
	"\a_RoomID\"p\n" +
	"\x06Damaku\x12$\n" +
	"\x04Meta\x18\x01 \x01(\v2\x10.pb.BasicMsgMetaR\x04Meta\x12\x10\n" +
	"\x03UID\x18\x02 \x01(\x04R\x03UID\x12\x18\n" +
	"\aContent\x18\x03 \x01(\tR\aContent\x12\x14\n" +
	"\x05Medal\x18\x04 \x01(\x04R\x05Medal\"\xa0\x02\n" +
	"\x04Gift\x12$\n" +
	"\x04Meta\x18\x01 \x01(\v2\x10.pb.BasicMsgMetaR\x04Meta\x12\x10\n" +
	"\x03TID\x18\x02 \x01(\x04R\x03TID\x12\x10\n" +
	"\x03UID\x18\x03 \x01(\x04R\x03UID\x12\x14\n" +
	"\x05Count\x18\x04 \x01(\rR\x05Count\x12%\n" +
	"\x04Info\x18\x05 \x01(\v2\x11.pb.Gift.GiftInfoR\x04Info\x125\n" +
	"\fOriginalInfo\x18\x06 \x01(\v2\x11.pb.Gift.GiftInfoR\fOriginalInfo\x12\x14\n" +
	"\x05Medal\x18\a \x01(\x04R\x05Medal\x1aD\n" +
	"\bGiftInfo\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\rR\x02ID\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x14\n" +
	"\x05Price\x18\x03 \x01(\rR\x05Price\"\xd7\x01\n" +
	"\x05Guard\x12$\n" +
	"\x04Meta\x18\x01 \x01(\v2\x10.pb.BasicMsgMetaR\x04Meta\x12\x10\n" +
	"\x03UID\x18\x02 \x01(\x04R\x03UID\x12\x14\n" +
	"\x05Price\x18\x03 \x01(\rR\x05Price\x123\n" +
	"\bGiftType\x18\x04 \x01(\x0e2\x17.pb.Guard.GuardGiftTypeR\bGiftType\"K\n" +
	"\rGuardGiftType\x12\x0f\n" +
	"\vUnknownType\x10\x00\x12\r\n" +
	"\bGovernor\x10\x91N\x12\f\n" +
	"\aAdmiral\x10\x92N\x12\f\n" +
	"\aCaptain\x10\x93N\"\xbd\x01\n" +
	"\tSuperChat\x12$\n" +
	"\x04Meta\x18\x01 \x01(\v2\x10.pb.BasicMsgMetaR\x04Meta\x12\x0e\n" +
	"\x02ID\x18\x02 \x01(\x04R\x02ID\x12\x10\n" +
	"\x03UID\x18\x03 \x01(\x04R\x03UID\x12\x18\n" +
	"\aMessage\x18\x04 \x01(\tR\aMessage\x12\"\n" +
	"\fMessageTrans\x18\x05 \x01(\tR\fMessageTrans\x12\x14\n" +
	"\x05Price\x18\x06 \x01(\rR\x05Price\x12\x14\n" +
	"\x05Medal\x18\a \x01(\x04R\x05Medal\"e\n" +
	"\x0fOnlineRankCount\x12$\n" +
	"\x04Meta\x18\x01 \x01(\v2\x10.pb.BasicMsgMetaR\x04Meta\x12\x14\n" +
	"\x05Count\x18\x02 \x01(\rR\x05Count\x12\x16\n" +
	"\x06Online\x18\x03 \x01(\rR\x06Online\"\xec\x01\n" +
	"\fOnlineRankV2\x12$\n" +
	"\x04Meta\x18\x01 \x01(\v2\x10.pb.BasicMsgMetaR\x04Meta\x123\n" +
	"\x04list\x18\x02 \x03(\v2\x1f.pb.OnlineRankV2.OnlineRankListR\x04list\x1a\x80\x01\n" +
	"\x0eOnlineRankList\x12\x12\n" +
	"\x04Rank\x18\x01 \x01(\rR\x04Rank\x12\x14\n" +
	"\x05Score\x18\x02 \x01(\rR\x05Score\x12\x10\n" +
	"\x03UID\x18\x03 \x01(\x04R\x03UID\x122\n" +
	"\n" +
	"GuardLevel\x18\x04 \x01(\x0e2\x12.pb.GuardLevelTypeR\n" +
	"GuardLevel*E\n" +
	"\x0eGuardLevelType\x12\v\n" +
	"\aNoGuard\x10\x00\x12\f\n" +
	"\bGovernor\x10\x01\x12\v\n" +
	"\aAdmiral\x10\x02\x12\v\n" +
	"\aCaptain\x10\x03B\fH\x01Z\bpb/agentb\x06proto3"

var (
	file_pb_agent_proto_rawDescOnce sync.Once
	file_pb_agent_proto_rawDescData []byte
)

func file_pb_agent_proto_rawDescGZIP() []byte {
	file_pb_agent_proto_rawDescOnce.Do(func() {
		file_pb_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_agent_proto_rawDesc), len(file_pb_agent_proto_rawDesc)))
	})
	return file_pb_agent_proto_rawDescData
}

var file_pb_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 8)
var file_pb_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_pb_agent_proto_goTypes = []any{
	(GuardLevelType)(0),                  // 0: pb.GuardLevelType
	(AgentControlResponse_StatusType)(0), // 1: pb.AgentControlResponse.StatusType
	(AgentInfo_AgentType)(0),             // 2: pb.AgentInfo.AgentType
	(AgentAction_AgentActionType)(0),     // 3: pb.AgentAction.AgentActionType
	(AgentStatus_BufferType)(0),          // 4: pb.AgentStatus.BufferType
	(AgentStatus_MetaCacheType)(0),       // 5: pb.AgentStatus.MetaCacheType
	(BasicMsgMeta_TraceStep)(0),          // 6: pb.BasicMsgMeta.TraceStep
	(Guard_GuardGiftType)(0),             // 7: pb.Guard.GuardGiftType
	(*AgentControlResponse)(nil),         // 8: pb.AgentControlResponse
	(*AgentInfo)(nil),                    // 9: pb.AgentInfo
	(*AgentInit)(nil),                    // 10: pb.AgentInit
	(*AgentAction)(nil),                  // 11: pb.AgentAction
	(*AgentStatus)(nil),                  // 12: pb.AgentStatus
	(*FansMedalMeta)(nil),                // 13: pb.FansMedalMeta
	(*UserInfoMeta)(nil),                 // 14: pb.UserInfoMeta
	(*BasicMsgMeta)(nil),                 // 15: pb.BasicMsgMeta
	(*Damaku)(nil),                       // 16: pb.Damaku
	(*Gift)(nil),                         // 17: pb.Gift
	(*Guard)(nil),                        // 18: pb.Guard
	(*SuperChat)(nil),                    // 19: pb.SuperChat
	(*OnlineRankCount)(nil),              // 20: pb.OnlineRankCount
	(*OnlineRankV2)(nil),                 // 21: pb.OnlineRankV2
	nil,                                  // 22: pb.AgentInit.HeaderEntry
	nil,                                  // 23: pb.AgentStatus.BufferEventCountEntry
	nil,                                  // 24: pb.AgentStatus.MetaCacheEntry
	(*AgentStatus_MetaCacheInfo)(nil),    // 25: pb.AgentStatus.MetaCacheInfo
	nil,                                  // 26: pb.BasicMsgMeta.TraceEntry
	(*Gift_GiftInfo)(nil),                // 27: pb.Gift.GiftInfo
	(*OnlineRankV2_OnlineRankList)(nil),  // 28: pb.OnlineRankV2.OnlineRankList
}
var file_pb_agent_proto_depIdxs = []int32{
	1,  // 0: pb.AgentControlResponse.Status:type_name -> pb.AgentControlResponse.StatusType
	2,  // 1: pb.AgentInfo.Type:type_name -> pb.AgentInfo.AgentType
	22, // 2: pb.AgentInit.Header:type_name -> pb.AgentInit.HeaderEntry
	3,  // 3: pb.AgentAction.Type:type_name -> pb.AgentAction.AgentActionType
	15, // 4: pb.AgentStatus.Meta:type_name -> pb.BasicMsgMeta
	23, // 5: pb.AgentStatus.BufferEventCount:type_name -> pb.AgentStatus.BufferEventCountEntry
	24, // 6: pb.AgentStatus.MetaCache:type_name -> pb.AgentStatus.MetaCacheEntry
	0,  // 7: pb.FansMedalMeta.GuardLevel:type_name -> pb.GuardLevelType
	26, // 8: pb.BasicMsgMeta.Trace:type_name -> pb.BasicMsgMeta.TraceEntry
	15, // 9: pb.Damaku.Meta:type_name -> pb.BasicMsgMeta
	15, // 10: pb.Gift.Meta:type_name -> pb.BasicMsgMeta
	27, // 11: pb.Gift.Info:type_name -> pb.Gift.GiftInfo
	27, // 12: pb.Gift.OriginalInfo:type_name -> pb.Gift.GiftInfo
	15, // 13: pb.Guard.Meta:type_name -> pb.BasicMsgMeta
	7,  // 14: pb.Guard.GiftType:type_name -> pb.Guard.GuardGiftType
	15, // 15: pb.SuperChat.Meta:type_name -> pb.BasicMsgMeta
	15, // 16: pb.OnlineRankCount.Meta:type_name -> pb.BasicMsgMeta
	15, // 17: pb.OnlineRankV2.Meta:type_name -> pb.BasicMsgMeta
	28, // 18: pb.OnlineRankV2.list:type_name -> pb.OnlineRankV2.OnlineRankList
	25, // 19: pb.AgentStatus.MetaCacheEntry.value:type_name -> pb.AgentStatus.MetaCacheInfo
	0,  // 20: pb.OnlineRankV2.OnlineRankList.GuardLevel:type_name -> pb.GuardLevelType
	21, // [21:21] is the sub-list for method output_type
	21, // [21:21] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_pb_agent_proto_init() }
func file_pb_agent_proto_init() {
	if File_pb_agent_proto != nil {
		return
	}
	file_pb_agent_proto_msgTypes[0].OneofWrappers = []any{}
	file_pb_agent_proto_msgTypes[2].OneofWrappers = []any{}
	file_pb_agent_proto_msgTypes[3].OneofWrappers = []any{}
	file_pb_agent_proto_msgTypes[6].OneofWrappers = []any{}
	file_pb_agent_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_agent_proto_rawDesc), len(file_pb_agent_proto_rawDesc)),
			NumEnums:      8,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_agent_proto_goTypes,
		DependencyIndexes: file_pb_agent_proto_depIdxs,
		EnumInfos:         file_pb_agent_proto_enumTypes,
		MessageInfos:      file_pb_agent_proto_msgTypes,
	}.Build()
	File_pb_agent_proto = out.File
	file_pb_agent_proto_goTypes = nil
	file_pb_agent_proto_depIdxs = nil
}
