// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.3
// 	protoc        v5.29.3
// source: pb/agent.proto

package agent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GuardLevelType int32

const (
	GuardLevelType_NoGuard  GuardLevelType = 0
	GuardLevelType_Governor GuardLevelType = 1
	GuardLevelType_Admiral  GuardLevelType = 2
	GuardLevelType_Captain  GuardLevelType = 3
)

// Enum value maps for GuardLevelType.
var (
	GuardLevelType_name = map[int32]string{
		0: "NoGuard",
		1: "Governor",
		2: "Admiral",
		3: "Captain",
	}
	GuardLevelType_value = map[string]int32{
		"NoGuard":  0,
		"Governor": 1,
		"Admiral":  2,
		"Captain":  3,
	}
)

func (x GuardLevelType) Enum() *GuardLevelType {
	p := new(GuardLevelType)
	*p = x
	return p
}

func (x GuardLevelType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GuardLevelType) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_agent_proto_enumTypes[0].Descriptor()
}

func (GuardLevelType) Type() protoreflect.EnumType {
	return &file_pb_agent_proto_enumTypes[0]
}

func (x GuardLevelType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GuardLevelType.Descriptor instead.
func (GuardLevelType) EnumDescriptor() ([]byte, []int) {
	return file_pb_agent_proto_rawDescGZIP(), []int{0}
}

type AgentInfo_AgentType int32

const (
	AgentInfo_UnknownAgent  AgentInfo_AgentType = 0
	AgentInfo_RealTimeAgent AgentInfo_AgentType = 1
	AgentInfo_PlaybackAgent AgentInfo_AgentType = 2
)

// Enum value maps for AgentInfo_AgentType.
var (
	AgentInfo_AgentType_name = map[int32]string{
		0: "UnknownAgent",
		1: "RealTimeAgent",
		2: "PlaybackAgent",
	}
	AgentInfo_AgentType_value = map[string]int32{
		"UnknownAgent":  0,
		"RealTimeAgent": 1,
		"PlaybackAgent": 2,
	}
)

func (x AgentInfo_AgentType) Enum() *AgentInfo_AgentType {
	p := new(AgentInfo_AgentType)
	*p = x
	return p
}

func (x AgentInfo_AgentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentInfo_AgentType) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_agent_proto_enumTypes[1].Descriptor()
}

func (AgentInfo_AgentType) Type() protoreflect.EnumType {
	return &file_pb_agent_proto_enumTypes[1]
}

func (x AgentInfo_AgentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentInfo_AgentType.Descriptor instead.
func (AgentInfo_AgentType) EnumDescriptor() ([]byte, []int) {
	return file_pb_agent_proto_rawDescGZIP(), []int{1, 0}
}

type AgentAction_AgentActionType int32

const (
	AgentAction_AddRoom AgentAction_AgentActionType = 0
	AgentAction_DelRoom AgentAction_AgentActionType = 1
)

// Enum value maps for AgentAction_AgentActionType.
var (
	AgentAction_AgentActionType_name = map[int32]string{
		0: "AddRoom",
		1: "DelRoom",
	}
	AgentAction_AgentActionType_value = map[string]int32{
		"AddRoom": 0,
		"DelRoom": 1,
	}
)

func (x AgentAction_AgentActionType) Enum() *AgentAction_AgentActionType {
	p := new(AgentAction_AgentActionType)
	*p = x
	return p
}

func (x AgentAction_AgentActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentAction_AgentActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_agent_proto_enumTypes[2].Descriptor()
}

func (AgentAction_AgentActionType) Type() protoreflect.EnumType {
	return &file_pb_agent_proto_enumTypes[2]
}

func (x AgentAction_AgentActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentAction_AgentActionType.Descriptor instead.
func (AgentAction_AgentActionType) EnumDescriptor() ([]byte, []int) {
	return file_pb_agent_proto_rawDescGZIP(), []int{3, 0}
}

type Guard_GuardGiftType int32

const (
	Guard_UnknownType Guard_GuardGiftType = 0
	Guard_Governor    Guard_GuardGiftType = 10001
	Guard_Admiral     Guard_GuardGiftType = 10002
	Guard_Captain     Guard_GuardGiftType = 10003
)

// Enum value maps for Guard_GuardGiftType.
var (
	Guard_GuardGiftType_name = map[int32]string{
		0:     "UnknownType",
		10001: "Governor",
		10002: "Admiral",
		10003: "Captain",
	}
	Guard_GuardGiftType_value = map[string]int32{
		"UnknownType": 0,
		"Governor":    10001,
		"Admiral":     10002,
		"Captain":     10003,
	}
)

func (x Guard_GuardGiftType) Enum() *Guard_GuardGiftType {
	p := new(Guard_GuardGiftType)
	*p = x
	return p
}

func (x Guard_GuardGiftType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Guard_GuardGiftType) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_agent_proto_enumTypes[3].Descriptor()
}

func (Guard_GuardGiftType) Type() protoreflect.EnumType {
	return &file_pb_agent_proto_enumTypes[3]
}

func (x Guard_GuardGiftType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Guard_GuardGiftType.Descriptor instead.
func (Guard_GuardGiftType) EnumDescriptor() ([]byte, []int) {
	return file_pb_agent_proto_rawDescGZIP(), []int{11, 0}
}

// normal response for request msg
type AgentControlResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        uint32                 `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"` // 0:OK, 1:Error
	Error         *string                `protobuf:"bytes,2,opt,name=Error,proto3,oneof" json:"Error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentControlResponse) Reset() {
	*x = AgentControlResponse{}
	mi := &file_pb_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentControlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentControlResponse) ProtoMessage() {}

func (x *AgentControlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentControlResponse.ProtoReflect.Descriptor instead.
func (*AgentControlResponse) Descriptor() ([]byte, []int) {
	return file_pb_agent_proto_rawDescGZIP(), []int{0}
}

func (x *AgentControlResponse) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AgentControlResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

// bind to agent.info when init
type AgentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Type          AgentInfo_AgentType    `protobuf:"varint,2,opt,name=Type,proto3,enum=pb.AgentInfo_AgentType" json:"Type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentInfo) Reset() {
	*x = AgentInfo{}
	mi := &file_pb_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentInfo) ProtoMessage() {}

func (x *AgentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pb_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentInfo.ProtoReflect.Descriptor instead.
func (*AgentInfo) Descriptor() ([]byte, []int) {
	return file_pb_agent_proto_rawDescGZIP(), []int{1}
}

func (x *AgentInfo) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *AgentInfo) GetType() AgentInfo_AgentType {
	if x != nil {
		return x.Type
	}
	return AgentInfo_UnknownAgent
}

// bind to control request agent.[AgentID].init
type AgentInit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BUVID         string                 `protobuf:"bytes,1,opt,name=BUVID,proto3" json:"BUVID,omitempty"`
	UID           string                 `protobuf:"bytes,2,opt,name=UID,proto3" json:"UID,omitempty"`
	Cookie        string                 `protobuf:"bytes,3,opt,name=Cookie,proto3" json:"Cookie,omitempty"`
	UA            *string                `protobuf:"bytes,4,opt,name=UA,proto3,oneof" json:"UA,omitempty"`
	Header        map[string]string      `protobuf:"bytes,5,rep,name=Header,proto3" json:"Header,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	PriorityMode  *uint32                `protobuf:"varint,6,opt,name=PriorityMode,proto3,oneof" json:"PriorityMode,omitempty"` // defined const at github.com/FishZe/go-bili-chat/client:PriorityMode
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentInit) Reset() {
	*x = AgentInit{}
	mi := &file_pb_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentInit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentInit) ProtoMessage() {}

func (x *AgentInit) ProtoReflect() protoreflect.Message {
	mi := &file_pb_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentInit.ProtoReflect.Descriptor instead.
func (*AgentInit) Descriptor() ([]byte, []int) {
	return file_pb_agent_proto_rawDescGZIP(), []int{2}
}

func (x *AgentInit) GetBUVID() string {
	if x != nil {
		return x.BUVID
	}
	return ""
}

func (x *AgentInit) GetUID() string {
	if x != nil {
		return x.UID
	}
	return ""
}

func (x *AgentInit) GetCookie() string {
	if x != nil {
		return x.Cookie
	}
	return ""
}

func (x *AgentInit) GetUA() string {
	if x != nil && x.UA != nil {
		return *x.UA
	}
	return ""
}

func (x *AgentInit) GetHeader() map[string]string {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *AgentInit) GetPriorityMode() uint32 {
	if x != nil && x.PriorityMode != nil {
		return *x.PriorityMode
	}
	return 0
}

// bind to control request agent.[AgentID].action
type AgentAction struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Type          AgentAction_AgentActionType `protobuf:"varint,1,opt,name=Type,proto3,enum=pb.AgentAction_AgentActionType" json:"Type,omitempty"`
	RoomID        *uint64                     `protobuf:"varint,2,opt,name=RoomID,proto3,oneof" json:"RoomID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentAction) Reset() {
	*x = AgentAction{}
	mi := &file_pb_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentAction) ProtoMessage() {}

func (x *AgentAction) ProtoReflect() protoreflect.Message {
	mi := &file_pb_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentAction.ProtoReflect.Descriptor instead.
func (*AgentAction) Descriptor() ([]byte, []int) {
	return file_pb_agent_proto_rawDescGZIP(), []int{3}
}

func (x *AgentAction) GetType() AgentAction_AgentActionType {
	if x != nil {
		return x.Type
	}
	return AgentAction_AddRoom
}

func (x *AgentAction) GetRoomID() uint64 {
	if x != nil && x.RoomID != nil {
		return *x.RoomID
	}
	return 0
}

// bind to agent.status
type AgentStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Watching      []uint32               `protobuf:"varint,1,rep,packed,name=Watching,proto3" json:"Watching,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentStatus) Reset() {
	*x = AgentStatus{}
	mi := &file_pb_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentStatus) ProtoMessage() {}

func (x *AgentStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pb_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentStatus.ProtoReflect.Descriptor instead.
func (*AgentStatus) Descriptor() ([]byte, []int) {
	return file_pb_agent_proto_rawDescGZIP(), []int{4}
}

func (x *AgentStatus) GetWatching() []uint32 {
	if x != nil {
		return x.Watching
	}
	return nil
}

type BasicMsgMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint32                 `protobuf:"varint,1,opt,name=Version,proto3" json:"Version,omitempty"`
	Agent         string                 `protobuf:"bytes,2,opt,name=Agent,proto3" json:"Agent,omitempty"`          // AgentID
	TimeStamp     uint64                 `protobuf:"varint,3,opt,name=TimeStamp,proto3" json:"TimeStamp,omitempty"` // MilliTimestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BasicMsgMeta) Reset() {
	*x = BasicMsgMeta{}
	mi := &file_pb_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BasicMsgMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasicMsgMeta) ProtoMessage() {}

func (x *BasicMsgMeta) ProtoReflect() protoreflect.Message {
	mi := &file_pb_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasicMsgMeta.ProtoReflect.Descriptor instead.
func (*BasicMsgMeta) Descriptor() ([]byte, []int) {
	return file_pb_agent_proto_rawDescGZIP(), []int{5}
}

func (x *BasicMsgMeta) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *BasicMsgMeta) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

func (x *BasicMsgMeta) GetTimeStamp() uint64 {
	if x != nil {
		return x.TimeStamp
	}
	return 0
}

type FansMedal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomUID       uint64                 `protobuf:"varint,1,opt,name=RoomUID,proto3" json:"RoomUID,omitempty"` // target user id
	Level         uint32                 `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	Light         bool                   `protobuf:"varint,3,opt,name=Light,proto3" json:"Light,omitempty"`
	GuardLevel    GuardLevelType         `protobuf:"varint,4,opt,name=GuardLevel,proto3,enum=pb.GuardLevelType" json:"GuardLevel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FansMedal) Reset() {
	*x = FansMedal{}
	mi := &file_pb_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FansMedal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FansMedal) ProtoMessage() {}

func (x *FansMedal) ProtoReflect() protoreflect.Message {
	mi := &file_pb_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FansMedal.ProtoReflect.Descriptor instead.
func (*FansMedal) Descriptor() ([]byte, []int) {
	return file_pb_agent_proto_rawDescGZIP(), []int{6}
}

func (x *FansMedal) GetRoomUID() uint64 {
	if x != nil {
		return x.RoomUID
	}
	return 0
}

func (x *FansMedal) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *FansMedal) GetLight() bool {
	if x != nil {
		return x.Light
	}
	return false
}

func (x *FansMedal) GetGuardLevel() GuardLevelType {
	if x != nil {
		return x.GuardLevel
	}
	return GuardLevelType_NoGuard
}

// bind to request agent.fansMedal
type FansMedalMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomUID       uint64                 `protobuf:"varint,1,opt,name=RoomUID,proto3" json:"RoomUID,omitempty"` // target user id
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FansMedalMeta) Reset() {
	*x = FansMedalMeta{}
	mi := &file_pb_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FansMedalMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FansMedalMeta) ProtoMessage() {}

func (x *FansMedalMeta) ProtoReflect() protoreflect.Message {
	mi := &file_pb_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FansMedalMeta.ProtoReflect.Descriptor instead.
func (*FansMedalMeta) Descriptor() ([]byte, []int) {
	return file_pb_agent_proto_rawDescGZIP(), []int{7}
}

func (x *FansMedalMeta) GetRoomUID() uint64 {
	if x != nil {
		return x.RoomUID
	}
	return 0
}

func (x *FansMedalMeta) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// bind to request agent.userInfoMeta
type UserInfoMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UID           uint64                 `protobuf:"varint,1,opt,name=UID,proto3" json:"UID,omitempty"`
	UserName      string                 `protobuf:"bytes,2,opt,name=UserName,proto3" json:"UserName,omitempty"`
	Face          string                 `protobuf:"bytes,3,opt,name=Face,proto3" json:"Face,omitempty"`
	Level         *uint32                `protobuf:"varint,4,opt,name=Level,proto3,oneof" json:"Level,omitempty"`             // available at superChat
	WealthLevel   *uint32                `protobuf:"varint,5,opt,name=WealthLevel,proto3,oneof" json:"WealthLevel,omitempty"` // available at gift
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfoMeta) Reset() {
	*x = UserInfoMeta{}
	mi := &file_pb_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfoMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoMeta) ProtoMessage() {}

func (x *UserInfoMeta) ProtoReflect() protoreflect.Message {
	mi := &file_pb_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoMeta.ProtoReflect.Descriptor instead.
func (*UserInfoMeta) Descriptor() ([]byte, []int) {
	return file_pb_agent_proto_rawDescGZIP(), []int{8}
}

func (x *UserInfoMeta) GetUID() uint64 {
	if x != nil {
		return x.UID
	}
	return 0
}

func (x *UserInfoMeta) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *UserInfoMeta) GetFace() string {
	if x != nil {
		return x.Face
	}
	return ""
}

func (x *UserInfoMeta) GetLevel() uint32 {
	if x != nil && x.Level != nil {
		return *x.Level
	}
	return 0
}

func (x *UserInfoMeta) GetWealthLevel() uint32 {
	if x != nil && x.WealthLevel != nil {
		return *x.WealthLevel
	}
	return 0
}

// bind to agent.damaku
type Damaku struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *BasicMsgMeta          `protobuf:"bytes,1,opt,name=Meta,proto3" json:"Meta,omitempty"`
	UID           uint64                 `protobuf:"varint,2,opt,name=UID,proto3" json:"UID,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=Content,proto3" json:"Content,omitempty"`
	Medal         *FansMedal             `protobuf:"bytes,4,opt,name=Medal,proto3" json:"Medal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Damaku) Reset() {
	*x = Damaku{}
	mi := &file_pb_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Damaku) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Damaku) ProtoMessage() {}

func (x *Damaku) ProtoReflect() protoreflect.Message {
	mi := &file_pb_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Damaku.ProtoReflect.Descriptor instead.
func (*Damaku) Descriptor() ([]byte, []int) {
	return file_pb_agent_proto_rawDescGZIP(), []int{9}
}

func (x *Damaku) GetMeta() *BasicMsgMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Damaku) GetUID() uint64 {
	if x != nil {
		return x.UID
	}
	return 0
}

func (x *Damaku) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Damaku) GetMedal() *FansMedal {
	if x != nil {
		return x.Medal
	}
	return nil
}

// bind to agent.gift
type Gift struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *BasicMsgMeta          `protobuf:"bytes,1,opt,name=Meta,proto3" json:"Meta,omitempty"`
	TID           uint64                 `protobuf:"varint,2,opt,name=TID,proto3" json:"TID,omitempty"` // gift msg id
	UID           uint64                 `protobuf:"varint,3,opt,name=UID,proto3" json:"UID,omitempty"`
	Count         uint32                 `protobuf:"varint,4,opt,name=Count,proto3" json:"Count,omitempty"`
	Info          *Gift_GiftInfo         `protobuf:"bytes,5,opt,name=Info,proto3" json:"Info,omitempty"`
	OriginalInfo  *Gift_GiftInfo         `protobuf:"bytes,6,opt,name=OriginalInfo,proto3" json:"OriginalInfo,omitempty"` // include blind gift
	Medal         *FansMedal             `protobuf:"bytes,7,opt,name=Medal,proto3" json:"Medal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Gift) Reset() {
	*x = Gift{}
	mi := &file_pb_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Gift) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gift) ProtoMessage() {}

func (x *Gift) ProtoReflect() protoreflect.Message {
	mi := &file_pb_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gift.ProtoReflect.Descriptor instead.
func (*Gift) Descriptor() ([]byte, []int) {
	return file_pb_agent_proto_rawDescGZIP(), []int{10}
}

func (x *Gift) GetMeta() *BasicMsgMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Gift) GetTID() uint64 {
	if x != nil {
		return x.TID
	}
	return 0
}

func (x *Gift) GetUID() uint64 {
	if x != nil {
		return x.UID
	}
	return 0
}

func (x *Gift) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *Gift) GetInfo() *Gift_GiftInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *Gift) GetOriginalInfo() *Gift_GiftInfo {
	if x != nil {
		return x.OriginalInfo
	}
	return nil
}

func (x *Gift) GetMedal() *FansMedal {
	if x != nil {
		return x.Medal
	}
	return nil
}

// bind to agent.guard
type Guard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *BasicMsgMeta          `protobuf:"bytes,1,opt,name=Meta,proto3" json:"Meta,omitempty"`
	UID           uint64                 `protobuf:"varint,2,opt,name=UID,proto3" json:"UID,omitempty"`
	Price         uint32                 `protobuf:"varint,3,opt,name=Price,proto3" json:"Price,omitempty"` // gold_seeds, = battery / 100 = RMB / 1000
	GiftType      Guard_GuardGiftType    `protobuf:"varint,4,opt,name=GiftType,proto3,enum=pb.Guard_GuardGiftType" json:"GiftType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Guard) Reset() {
	*x = Guard{}
	mi := &file_pb_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Guard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Guard) ProtoMessage() {}

func (x *Guard) ProtoReflect() protoreflect.Message {
	mi := &file_pb_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Guard.ProtoReflect.Descriptor instead.
func (*Guard) Descriptor() ([]byte, []int) {
	return file_pb_agent_proto_rawDescGZIP(), []int{11}
}

func (x *Guard) GetMeta() *BasicMsgMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Guard) GetUID() uint64 {
	if x != nil {
		return x.UID
	}
	return 0
}

func (x *Guard) GetPrice() uint32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Guard) GetGiftType() Guard_GuardGiftType {
	if x != nil {
		return x.GiftType
	}
	return Guard_UnknownType
}

type SuperChat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *BasicMsgMeta          `protobuf:"bytes,1,opt,name=Meta,proto3" json:"Meta,omitempty"`
	ID            uint64                 `protobuf:"varint,2,opt,name=ID,proto3" json:"ID,omitempty"` // sc id
	UID           uint64                 `protobuf:"varint,3,opt,name=UID,proto3" json:"UID,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=Message,proto3" json:"Message,omitempty"`
	MessageTrans  string                 `protobuf:"bytes,5,opt,name=MessageTrans,proto3" json:"MessageTrans,omitempty"`
	Price         uint32                 `protobuf:"varint,6,opt,name=Price,proto3" json:"Price,omitempty"` // RMB, = battery / 10
	Medal         *FansMedal             `protobuf:"bytes,7,opt,name=Medal,proto3" json:"Medal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuperChat) Reset() {
	*x = SuperChat{}
	mi := &file_pb_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuperChat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuperChat) ProtoMessage() {}

func (x *SuperChat) ProtoReflect() protoreflect.Message {
	mi := &file_pb_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuperChat.ProtoReflect.Descriptor instead.
func (*SuperChat) Descriptor() ([]byte, []int) {
	return file_pb_agent_proto_rawDescGZIP(), []int{12}
}

func (x *SuperChat) GetMeta() *BasicMsgMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *SuperChat) GetID() uint64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *SuperChat) GetUID() uint64 {
	if x != nil {
		return x.UID
	}
	return 0
}

func (x *SuperChat) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SuperChat) GetMessageTrans() string {
	if x != nil {
		return x.MessageTrans
	}
	return ""
}

func (x *SuperChat) GetPrice() uint32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *SuperChat) GetMedal() *FansMedal {
	if x != nil {
		return x.Medal
	}
	return nil
}

// bind to agent.online
type OnlineRankCount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *BasicMsgMeta          `protobuf:"bytes,1,opt,name=Meta,proto3" json:"Meta,omitempty"`
	Count         uint32                 `protobuf:"varint,2,opt,name=Count,proto3" json:"Count,omitempty"`
	Online        uint32                 `protobuf:"varint,3,opt,name=Online,proto3" json:"Online,omitempty"` // current using
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnlineRankCount) Reset() {
	*x = OnlineRankCount{}
	mi := &file_pb_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnlineRankCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineRankCount) ProtoMessage() {}

func (x *OnlineRankCount) ProtoReflect() protoreflect.Message {
	mi := &file_pb_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineRankCount.ProtoReflect.Descriptor instead.
func (*OnlineRankCount) Descriptor() ([]byte, []int) {
	return file_pb_agent_proto_rawDescGZIP(), []int{13}
}

func (x *OnlineRankCount) GetMeta() *BasicMsgMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *OnlineRankCount) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *OnlineRankCount) GetOnline() uint32 {
	if x != nil {
		return x.Online
	}
	return 0
}

// bind to agent.onlineV2
type OnlineRankV2 struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Meta          *BasicMsgMeta                  `protobuf:"bytes,1,opt,name=Meta,proto3" json:"Meta,omitempty"`
	List          []*OnlineRankV2_OnlineRankList `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnlineRankV2) Reset() {
	*x = OnlineRankV2{}
	mi := &file_pb_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnlineRankV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineRankV2) ProtoMessage() {}

func (x *OnlineRankV2) ProtoReflect() protoreflect.Message {
	mi := &file_pb_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineRankV2.ProtoReflect.Descriptor instead.
func (*OnlineRankV2) Descriptor() ([]byte, []int) {
	return file_pb_agent_proto_rawDescGZIP(), []int{14}
}

func (x *OnlineRankV2) GetMeta() *BasicMsgMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *OnlineRankV2) GetList() []*OnlineRankV2_OnlineRankList {
	if x != nil {
		return x.List
	}
	return nil
}

type Gift_GiftInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            uint32                 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Price         uint32                 `protobuf:"varint,3,opt,name=Price,proto3" json:"Price,omitempty"` // gold_seeds, = battery / 100 = RMB / 1000
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Gift_GiftInfo) Reset() {
	*x = Gift_GiftInfo{}
	mi := &file_pb_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Gift_GiftInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gift_GiftInfo) ProtoMessage() {}

func (x *Gift_GiftInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pb_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gift_GiftInfo.ProtoReflect.Descriptor instead.
func (*Gift_GiftInfo) Descriptor() ([]byte, []int) {
	return file_pb_agent_proto_rawDescGZIP(), []int{10, 0}
}

func (x *Gift_GiftInfo) GetID() uint32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Gift_GiftInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Gift_GiftInfo) GetPrice() uint32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type OnlineRankV2_OnlineRankList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rank          uint32                 `protobuf:"varint,1,opt,name=Rank,proto3" json:"Rank,omitempty"`
	Score         uint32                 `protobuf:"varint,2,opt,name=Score,proto3" json:"Score,omitempty"`
	UID           uint64                 `protobuf:"varint,3,opt,name=UID,proto3" json:"UID,omitempty"`
	GuardLevel    GuardLevelType         `protobuf:"varint,4,opt,name=GuardLevel,proto3,enum=pb.GuardLevelType" json:"GuardLevel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnlineRankV2_OnlineRankList) Reset() {
	*x = OnlineRankV2_OnlineRankList{}
	mi := &file_pb_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnlineRankV2_OnlineRankList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineRankV2_OnlineRankList) ProtoMessage() {}

func (x *OnlineRankV2_OnlineRankList) ProtoReflect() protoreflect.Message {
	mi := &file_pb_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineRankV2_OnlineRankList.ProtoReflect.Descriptor instead.
func (*OnlineRankV2_OnlineRankList) Descriptor() ([]byte, []int) {
	return file_pb_agent_proto_rawDescGZIP(), []int{14, 0}
}

func (x *OnlineRankV2_OnlineRankList) GetRank() uint32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *OnlineRankV2_OnlineRankList) GetScore() uint32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *OnlineRankV2_OnlineRankList) GetUID() uint64 {
	if x != nil {
		return x.UID
	}
	return 0
}

func (x *OnlineRankV2_OnlineRankList) GetGuardLevel() GuardLevelType {
	if x != nil {
		return x.GuardLevel
	}
	return GuardLevelType_NoGuard
}

var File_pb_agent_proto protoreflect.FileDescriptor

var file_pb_agent_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x70, 0x62, 0x2f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x02, 0x70, 0x62, 0x22, 0x53, 0x0a, 0x14, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6e,
	0x74, 0x72, 0x6f, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x19, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x88, 0x01, 0x01, 0x42,
	0x08, 0x0a, 0x06, 0x5f, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x8d, 0x01, 0x0a, 0x09, 0x41, 0x67,
	0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x2b, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74,
	0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04,
	0x54, 0x79, 0x70, 0x65, 0x22, 0x43, 0x0a, 0x09, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x10, 0x0a, 0x0c, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x41, 0x67, 0x65, 0x6e,
	0x74, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x52, 0x65, 0x61, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x41,
	0x67, 0x65, 0x6e, 0x74, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x50, 0x6c, 0x61, 0x79, 0x62, 0x61,
	0x63, 0x6b, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x10, 0x02, 0x22, 0x8f, 0x02, 0x0a, 0x09, 0x41, 0x67,
	0x65, 0x6e, 0x74, 0x49, 0x6e, 0x69, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x42, 0x55, 0x56, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x42, 0x55, 0x56, 0x49, 0x44, 0x12, 0x10, 0x0a,
	0x03, 0x55, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x55, 0x49, 0x44, 0x12,
	0x16, 0x0a, 0x06, 0x43, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x43, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x12, 0x13, 0x0a, 0x02, 0x55, 0x41, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x02, 0x55, 0x41, 0x88, 0x01, 0x01, 0x12, 0x31, 0x0a, 0x06,
	0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70,
	0x62, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x69, 0x74, 0x2e, 0x48, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12,
	0x27, 0x0a, 0x0c, 0x50, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x4d, 0x6f, 0x64, 0x65, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x01, 0x52, 0x0c, 0x50, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74,
	0x79, 0x4d, 0x6f, 0x64, 0x65, 0x88, 0x01, 0x01, 0x1a, 0x39, 0x0a, 0x0b, 0x48, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a,
	0x02, 0x38, 0x01, 0x42, 0x05, 0x0a, 0x03, 0x5f, 0x55, 0x41, 0x42, 0x0f, 0x0a, 0x0d, 0x5f, 0x50,
	0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x4d, 0x6f, 0x64, 0x65, 0x22, 0x97, 0x01, 0x0a, 0x0b,
	0x41, 0x67, 0x65, 0x6e, 0x74, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x33, 0x0a, 0x04, 0x54,
	0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1f, 0x2e, 0x70, 0x62, 0x2e, 0x41,
	0x67, 0x65, 0x6e, 0x74, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74,
	0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x1b, 0x0a, 0x06, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04,
	0x48, 0x00, 0x52, 0x06, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x88, 0x01, 0x01, 0x22, 0x2b, 0x0a,
	0x0f, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x0b, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x52, 0x6f, 0x6f, 0x6d, 0x10, 0x00, 0x12, 0x0b, 0x0a,
	0x07, 0x44, 0x65, 0x6c, 0x52, 0x6f, 0x6f, 0x6d, 0x10, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x52,
	0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x22, 0x29, 0x0a, 0x0b, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x57, 0x61, 0x74, 0x63, 0x68, 0x69, 0x6e, 0x67,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x08, 0x57, 0x61, 0x74, 0x63, 0x68, 0x69, 0x6e, 0x67,
	0x22, 0x5c, 0x0a, 0x0c, 0x42, 0x61, 0x73, 0x69, 0x63, 0x4d, 0x73, 0x67, 0x4d, 0x65, 0x74, 0x61,
	0x12, 0x18, 0x0a, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x41, 0x67,
	0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x41, 0x67, 0x65, 0x6e, 0x74,
	0x12, 0x1c, 0x0a, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x85,
	0x01, 0x0a, 0x09, 0x46, 0x61, 0x6e, 0x73, 0x4d, 0x65, 0x64, 0x61, 0x6c, 0x12, 0x18, 0x0a, 0x07,
	0x52, 0x6f, 0x6f, 0x6d, 0x55, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x52,
	0x6f, 0x6f, 0x6d, 0x55, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x14, 0x0a, 0x05,
	0x4c, 0x69, 0x67, 0x68, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x4c, 0x69, 0x67,
	0x68, 0x74, 0x12, 0x32, 0x0a, 0x0a, 0x47, 0x75, 0x61, 0x72, 0x64, 0x4c, 0x65, 0x76, 0x65, 0x6c,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x75, 0x61, 0x72,
	0x64, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0a, 0x47, 0x75, 0x61, 0x72,
	0x64, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x22, 0x3d, 0x0a, 0x0d, 0x46, 0x61, 0x6e, 0x73, 0x4d, 0x65,
	0x64, 0x61, 0x6c, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x52, 0x6f, 0x6f, 0x6d, 0x55,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x52, 0x6f, 0x6f, 0x6d, 0x55, 0x49,
	0x44, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0xac, 0x01, 0x0a, 0x0c, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e,
	0x66, 0x6f, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x03, 0x55, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x55, 0x73, 0x65, 0x72,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x46, 0x61, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x46, 0x61, 0x63, 0x65, 0x12, 0x19, 0x0a, 0x05, 0x4c, 0x65, 0x76, 0x65,
	0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x00, 0x52, 0x05, 0x4c, 0x65, 0x76, 0x65, 0x6c,
	0x88, 0x01, 0x01, 0x12, 0x25, 0x0a, 0x0b, 0x57, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x4c, 0x65, 0x76,
	0x65, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x01, 0x52, 0x0b, 0x57, 0x65, 0x61, 0x6c,
	0x74, 0x68, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x88, 0x01, 0x01, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x4c,
	0x65, 0x76, 0x65, 0x6c, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x57, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x4c,
	0x65, 0x76, 0x65, 0x6c, 0x22, 0x7f, 0x0a, 0x06, 0x44, 0x61, 0x6d, 0x61, 0x6b, 0x75, 0x12, 0x24,
	0x0a, 0x04, 0x4d, 0x65, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70,
	0x62, 0x2e, 0x42, 0x61, 0x73, 0x69, 0x63, 0x4d, 0x73, 0x67, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x04,
	0x4d, 0x65, 0x74, 0x61, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x03, 0x55, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x12, 0x23, 0x0a, 0x05, 0x4d, 0x65, 0x64, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x46, 0x61, 0x6e, 0x73, 0x4d, 0x65, 0x64, 0x61, 0x6c, 0x52, 0x05,
	0x4d, 0x65, 0x64, 0x61, 0x6c, 0x22, 0xaf, 0x02, 0x0a, 0x04, 0x47, 0x69, 0x66, 0x74, 0x12, 0x24,
	0x0a, 0x04, 0x4d, 0x65, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70,
	0x62, 0x2e, 0x42, 0x61, 0x73, 0x69, 0x63, 0x4d, 0x73, 0x67, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x04,
	0x4d, 0x65, 0x74, 0x61, 0x12, 0x10, 0x0a, 0x03, 0x54, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x03, 0x54, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x49, 0x44, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x03, 0x55, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x25,
	0x0a, 0x04, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70,
	0x62, 0x2e, 0x47, 0x69, 0x66, 0x74, 0x2e, 0x47, 0x69, 0x66, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x04, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x35, 0x0a, 0x0c, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61,
	0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x62,
	0x2e, 0x47, 0x69, 0x66, 0x74, 0x2e, 0x47, 0x69, 0x66, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0c,
	0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x23, 0x0a, 0x05,
	0x4d, 0x65, 0x64, 0x61, 0x6c, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62,
	0x2e, 0x46, 0x61, 0x6e, 0x73, 0x4d, 0x65, 0x64, 0x61, 0x6c, 0x52, 0x05, 0x4d, 0x65, 0x64, 0x61,
	0x6c, 0x1a, 0x44, 0x0a, 0x08, 0x47, 0x69, 0x66, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a,
	0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x49, 0x44, 0x12, 0x12, 0x0a,
	0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x05, 0x50, 0x72, 0x69, 0x63, 0x65, 0x22, 0xd7, 0x01, 0x0a, 0x05, 0x47, 0x75, 0x61, 0x72,
	0x64, 0x12, 0x24, 0x0a, 0x04, 0x4d, 0x65, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x61, 0x73, 0x69, 0x63, 0x4d, 0x73, 0x67, 0x4d, 0x65, 0x74,
	0x61, 0x52, 0x04, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x49, 0x44, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x55, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x50, 0x72, 0x69,
	0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12,
	0x33, 0x0a, 0x08, 0x47, 0x69, 0x66, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x75, 0x61, 0x72, 0x64, 0x2e, 0x47, 0x75, 0x61,
	0x72, 0x64, 0x47, 0x69, 0x66, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x47, 0x69, 0x66, 0x74,
	0x54, 0x79, 0x70, 0x65, 0x22, 0x4b, 0x0a, 0x0d, 0x47, 0x75, 0x61, 0x72, 0x64, 0x47, 0x69, 0x66,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e,
	0x54, 0x79, 0x70, 0x65, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x08, 0x47, 0x6f, 0x76, 0x65, 0x72, 0x6e,
	0x6f, 0x72, 0x10, 0x91, 0x4e, 0x12, 0x0c, 0x0a, 0x07, 0x41, 0x64, 0x6d, 0x69, 0x72, 0x61, 0x6c,
	0x10, 0x92, 0x4e, 0x12, 0x0c, 0x0a, 0x07, 0x43, 0x61, 0x70, 0x74, 0x61, 0x69, 0x6e, 0x10, 0x93,
	0x4e, 0x22, 0xcc, 0x01, 0x0a, 0x09, 0x53, 0x75, 0x70, 0x65, 0x72, 0x43, 0x68, 0x61, 0x74, 0x12,
	0x24, 0x0a, 0x04, 0x4d, 0x65, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x70, 0x62, 0x2e, 0x42, 0x61, 0x73, 0x69, 0x63, 0x4d, 0x73, 0x67, 0x4d, 0x65, 0x74, 0x61, 0x52,
	0x04, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x02, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x03, 0x55, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x22, 0x0a, 0x0c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x23, 0x0a, 0x05, 0x4d,
	0x65, 0x64, 0x61, 0x6c, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e,
	0x46, 0x61, 0x6e, 0x73, 0x4d, 0x65, 0x64, 0x61, 0x6c, 0x52, 0x05, 0x4d, 0x65, 0x64, 0x61, 0x6c,
	0x22, 0x65, 0x0a, 0x0f, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x61, 0x6e, 0x6b, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x24, 0x0a, 0x04, 0x4d, 0x65, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x61, 0x73, 0x69, 0x63, 0x4d, 0x73, 0x67, 0x4d,
	0x65, 0x74, 0x61, 0x52, 0x04, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x06, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x22, 0xec, 0x01, 0x0a, 0x0c, 0x4f, 0x6e, 0x6c, 0x69,
	0x6e, 0x65, 0x52, 0x61, 0x6e, 0x6b, 0x56, 0x32, 0x12, 0x24, 0x0a, 0x04, 0x4d, 0x65, 0x74, 0x61,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x61, 0x73, 0x69,
	0x63, 0x4d, 0x73, 0x67, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x04, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x33,
	0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x70,
	0x62, 0x2e, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x61, 0x6e, 0x6b, 0x56, 0x32, 0x2e, 0x4f,
	0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x61, 0x6e, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x04, 0x6c,
	0x69, 0x73, 0x74, 0x1a, 0x80, 0x01, 0x0a, 0x0e, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x61,
	0x6e, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x52, 0x61, 0x6e, 0x6b, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x52, 0x61, 0x6e, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x63,
	0x6f, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x53, 0x63, 0x6f, 0x72, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x55, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x55,
	0x49, 0x44, 0x12, 0x32, 0x0a, 0x0a, 0x47, 0x75, 0x61, 0x72, 0x64, 0x4c, 0x65, 0x76, 0x65, 0x6c,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x75, 0x61, 0x72,
	0x64, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0a, 0x47, 0x75, 0x61, 0x72,
	0x64, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x2a, 0x45, 0x0a, 0x0e, 0x47, 0x75, 0x61, 0x72, 0x64, 0x4c,
	0x65, 0x76, 0x65, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x4e, 0x6f, 0x47, 0x75,
	0x61, 0x72, 0x64, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x47, 0x6f, 0x76, 0x65, 0x72, 0x6e, 0x6f,
	0x72, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x41, 0x64, 0x6d, 0x69, 0x72, 0x61, 0x6c, 0x10, 0x02,
	0x12, 0x0b, 0x0a, 0x07, 0x43, 0x61, 0x70, 0x74, 0x61, 0x69, 0x6e, 0x10, 0x03, 0x42, 0x0a, 0x5a,
	0x08, 0x70, 0x62, 0x2f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_pb_agent_proto_rawDescOnce sync.Once
	file_pb_agent_proto_rawDescData = file_pb_agent_proto_rawDesc
)

func file_pb_agent_proto_rawDescGZIP() []byte {
	file_pb_agent_proto_rawDescOnce.Do(func() {
		file_pb_agent_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_agent_proto_rawDescData)
	})
	return file_pb_agent_proto_rawDescData
}

var file_pb_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_pb_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_pb_agent_proto_goTypes = []any{
	(GuardLevelType)(0),                 // 0: pb.GuardLevelType
	(AgentInfo_AgentType)(0),            // 1: pb.AgentInfo.AgentType
	(AgentAction_AgentActionType)(0),    // 2: pb.AgentAction.AgentActionType
	(Guard_GuardGiftType)(0),            // 3: pb.Guard.GuardGiftType
	(*AgentControlResponse)(nil),        // 4: pb.AgentControlResponse
	(*AgentInfo)(nil),                   // 5: pb.AgentInfo
	(*AgentInit)(nil),                   // 6: pb.AgentInit
	(*AgentAction)(nil),                 // 7: pb.AgentAction
	(*AgentStatus)(nil),                 // 8: pb.AgentStatus
	(*BasicMsgMeta)(nil),                // 9: pb.BasicMsgMeta
	(*FansMedal)(nil),                   // 10: pb.FansMedal
	(*FansMedalMeta)(nil),               // 11: pb.FansMedalMeta
	(*UserInfoMeta)(nil),                // 12: pb.UserInfoMeta
	(*Damaku)(nil),                      // 13: pb.Damaku
	(*Gift)(nil),                        // 14: pb.Gift
	(*Guard)(nil),                       // 15: pb.Guard
	(*SuperChat)(nil),                   // 16: pb.SuperChat
	(*OnlineRankCount)(nil),             // 17: pb.OnlineRankCount
	(*OnlineRankV2)(nil),                // 18: pb.OnlineRankV2
	nil,                                 // 19: pb.AgentInit.HeaderEntry
	(*Gift_GiftInfo)(nil),               // 20: pb.Gift.GiftInfo
	(*OnlineRankV2_OnlineRankList)(nil), // 21: pb.OnlineRankV2.OnlineRankList
}
var file_pb_agent_proto_depIdxs = []int32{
	1,  // 0: pb.AgentInfo.Type:type_name -> pb.AgentInfo.AgentType
	19, // 1: pb.AgentInit.Header:type_name -> pb.AgentInit.HeaderEntry
	2,  // 2: pb.AgentAction.Type:type_name -> pb.AgentAction.AgentActionType
	0,  // 3: pb.FansMedal.GuardLevel:type_name -> pb.GuardLevelType
	9,  // 4: pb.Damaku.Meta:type_name -> pb.BasicMsgMeta
	10, // 5: pb.Damaku.Medal:type_name -> pb.FansMedal
	9,  // 6: pb.Gift.Meta:type_name -> pb.BasicMsgMeta
	20, // 7: pb.Gift.Info:type_name -> pb.Gift.GiftInfo
	20, // 8: pb.Gift.OriginalInfo:type_name -> pb.Gift.GiftInfo
	10, // 9: pb.Gift.Medal:type_name -> pb.FansMedal
	9,  // 10: pb.Guard.Meta:type_name -> pb.BasicMsgMeta
	3,  // 11: pb.Guard.GiftType:type_name -> pb.Guard.GuardGiftType
	9,  // 12: pb.SuperChat.Meta:type_name -> pb.BasicMsgMeta
	10, // 13: pb.SuperChat.Medal:type_name -> pb.FansMedal
	9,  // 14: pb.OnlineRankCount.Meta:type_name -> pb.BasicMsgMeta
	9,  // 15: pb.OnlineRankV2.Meta:type_name -> pb.BasicMsgMeta
	21, // 16: pb.OnlineRankV2.list:type_name -> pb.OnlineRankV2.OnlineRankList
	0,  // 17: pb.OnlineRankV2.OnlineRankList.GuardLevel:type_name -> pb.GuardLevelType
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_pb_agent_proto_init() }
func file_pb_agent_proto_init() {
	if File_pb_agent_proto != nil {
		return
	}
	file_pb_agent_proto_msgTypes[0].OneofWrappers = []any{}
	file_pb_agent_proto_msgTypes[2].OneofWrappers = []any{}
	file_pb_agent_proto_msgTypes[3].OneofWrappers = []any{}
	file_pb_agent_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_agent_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_agent_proto_goTypes,
		DependencyIndexes: file_pb_agent_proto_depIdxs,
		EnumInfos:         file_pb_agent_proto_enumTypes,
		MessageInfos:      file_pb_agent_proto_msgTypes,
	}.Build()
	File_pb_agent_proto = out.File
	file_pb_agent_proto_rawDesc = nil
	file_pb_agent_proto_goTypes = nil
	file_pb_agent_proto_depIdxs = nil
}
